name: CI-CD

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  tests:

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 14, lts/*, current ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Tests
        run: npm run test:ci

  deploy:

    name: Deploy into production branch

    runs-on: ubuntu-latest

    steps:
      - name: Merge main into prod
      - uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: prod
          github_token: ${{ github.token }}
